services:
  nextjs:
    build: .
    container_name: project-3_fe
    network_mode: "host"
    restart: always
    ports:
      - "5112:5112"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
